In [28]:
class myLinearRegression:
    def __init__(self):
        self.m=None
        self.b=None

    def fit(self,X_train,y_train):
            numerator=0
            denomintator=0
            for i in range(X_train.shape[0]):
                numerator+=((X_train[i] - X_train.mean())*(y_train[i] - y_train.mean()))
                denomintator+=((X_train[i] - X_train.mean())**2)
                self.m=numerator/denomintator
                self.b=y_train.mean() - self.m*X_train.mean()
                print(self.m)
                print(self.b)


    def predict(self, X_test):

        print(self.m * X_test + self.b)


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\devan\OneDrive\Desktop\ML Datasets and Notes\placement.csv")

In [3]:
df.head()

cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [4]:
X=df.iloc[:,0:1].values
y=df.iloc[:,1].values

In [6]:
X,y

(array([[6.89],
        [5.12],
        [7.82],
        [7.42],
        [6.94],
        [7.89],
        [6.73],
        [6.75],
        [6.09],
        [8.31],
        [5.32],
        [6.61],
        [8.94],
        [6.93],
        [7.73],
        [7.25],
        [6.84],
        [5.38],
        [6.94],
        [7.48],
        [7.28],
        [6.85],
        [6.14],
        [6.19],
        [6.53],
        [7.28],
        [8.31],
        [5.42],
        [5.94],
        [7.15],
        [7.36],
        [8.1 ],
        [6.96],
        [6.35],
        [7.34],
        [6.87],
        [5.99],
        [5.9 ],
        [8.62],
        [7.43],
        [9.38],
        [6.89],
        [5.95],
        [7.66],
        [5.09],
        [7.87],
        [6.07],
        [5.84],
        [8.63],
        [8.87],
        [9.58],
        [9.26],
        [8.37],
        [6.47],
        [6.86],
        [8.2 ],
        [5.84],
        [6.6 ],
        [6.92],
        [7.56],
        [5.61],
        [5.48],
        

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [8]:
X_train.shape

(160, 1)

In [29]:
lr=myLinearRegression()
lr.fit(X_train[:4,0],y_train[:4])

0.862903225806453
-3.3829032258064613
0.5338566396079032
-1.1157722468984534
0.5605909977465962
-1.2999719744740479
0.5585039936404588
-1.2855925161827613


In [30]:
lr.fit(X_train,y_train)

[-1.32201309]
[12.34849427]
[0.71103427]
[-1.97889875]
[0.59117428]
[-1.13421547]
[0.60310091]
[-1.21826536]
[0.50663548]
[-0.53844936]
[0.53176561]
[-0.71554773]
[0.54705335]
[-0.8232842]
[0.54537177]
[-0.81143371]
[0.53634919]
[-0.74784935]
[0.57400559]
[-1.01322338]
[0.57550268]
[-1.02377375]
[0.58331079]
[-1.07879946]
[0.5676912]
[-0.96872432]
[0.54692689]
[-0.82239303]
[0.54497128]
[-0.80861133]
[0.54586955]
[-0.81494167]
[0.54664387]
[-0.82039853]
[0.54611819]
[-0.81669395]
[0.52280657]
[-0.65241111]
[0.50918591]
[-0.5564229]
[0.52420832]
[-0.6622896]
[0.52327345]
[-0.65570133]
[0.53225695]
[-0.71901027]
[0.52642784]
[-0.67793107]
[0.53967698]
[-0.77130108]
[0.55255996]
[-0.86209065]
[0.55166113]
[-0.85575637]
[0.54353309]
[-0.79847607]
[0.52015856]
[-0.63374989]
[0.51279841]
[-0.58188113]
[0.51042601]
[-0.56516219]
[0.50982862]
[-0.56095224]
[0.50993958]
[-0.56173423]
[0.50470877]
[-0.52487139]
[0.5081344]
[-0.54901266]
[0.50803698]
[-0.54832613]
[0.51883363]
[-0.62441281]
[0.51

In [31]:
X_test

array([[6.94],
       [6.22],
       [6.33],
       [7.69],
       [7.09],
       [5.88],
       [7.89],
       [6.07],
       [8.94],
       [7.37],
       [5.48],
       [7.33],
       [6.19],
       [7.08],
       [7.63],
       [6.75],
       [6.35],
       [6.68],
       [5.9 ],
       [6.85],
       [7.28],
       [5.84],
       [7.87],
       [8.71],
       [5.61],
       [5.1 ],
       [7.14],
       [6.31],
       [5.12],
       [5.09],
       [6.84],
       [8.2 ],
       [6.3 ],
       [5.42],
       [6.14],
       [8.11],
       [7.29],
       [6.94],
       [8.44],
       [6.13]])

In [34]:
print(lr.predict(X_test))

[[2.97012606]
 [2.55516816]
 [2.61856451]
 [3.40237388]
 [3.05657563]
 [2.35921582]
 [3.51763996]
 [2.4687186 ]
 [4.1227869 ]
 [3.21794814]
 [2.12868365]
 [3.19489493]
 [2.53787825]
 [3.05081232]
 [3.36779405]
 [2.86062328]
 [2.63009112]
 [2.82028015]
 [2.37074243]
 [2.91825632]
 [3.1660784 ]
 [2.3361626 ]
 [3.50611335]
 [3.9902309 ]
 [2.20360661]
 [1.90967809]
 [3.08539215]
 [2.6070379 ]
 [1.9212047 ]
 [1.90391479]
 [2.91249302]
 [3.69630239]
 [2.60127459]
 [2.09410383]
 [2.50906173]
 [3.64443265]
 [3.17184171]
 [2.97012606]
 [3.83462169]
 [2.50329842]]
None


In [35]:
y_test

array([2.98, 2.87, 2.59, 3.83, 3.64, 2.08, 2.99, 2.46, 3.65, 3.08, 1.61,
       3.16, 2.72, 2.85, 3.44, 2.48, 2.73, 2.49, 2.43, 3.44, 2.72, 2.18,
       3.58, 4.08, 2.19, 2.3 , 3.03, 3.18, 2.01, 1.86, 2.35, 3.39, 2.73,
       2.25, 2.3 , 4.06, 3.12, 3.57, 3.49, 2.19])

In [36]:
from sklearn.metrics import r2_score
print(r2_score(y_test,lr.predict(X_test)))

[[2.97012606]
 [2.55516816]
 [2.61856451]
 [3.40237388]
 [3.05657563]
 [2.35921582]
 [3.51763996]
 [2.4687186 ]
 [4.1227869 ]
 [3.21794814]
 [2.12868365]
 [3.19489493]
 [2.53787825]
 [3.05081232]
 [3.36779405]
 [2.86062328]
 [2.63009112]
 [2.82028015]
 [2.37074243]
 [2.91825632]
 [3.1660784 ]
 [2.3361626 ]
 [3.50611335]
 [3.9902309 ]
 [2.20360661]
 [1.90967809]
 [3.08539215]
 [2.6070379 ]
 [1.9212047 ]
 [1.90391479]
 [2.91249302]
 [3.69630239]
 [2.60127459]
 [2.09410383]
 [2.50906173]
 [3.64443265]
 [3.17184171]
 [2.97012606]
 [3.83462169]
 [2.50329842]]


InvalidParameterError: The 'y_pred' parameter of r2_score must be an array-like. Got None instead.