In [29]:
import numpy as np
from sklearn.datasets import load_diabetes

In [30]:
X,y=load_diabetes(return_X_y=True)
X.shape

(442, 10)

In [31]:
y.shape

(442,)

# using sklearn LinearRegression

In [32]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [33]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [34]:
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [35]:
model.predict(X_test)

array([147.31378366, 134.8055264 ,  60.46184987, 155.06039239,
        73.37575811, 123.03940644, 188.72963279,  69.95248962,
        99.9343472 , 119.39950869, 224.17242185, 181.9774137 ,
        98.40216392,  92.53207427, 120.61217603, 152.18930744,
       119.7910676 , 204.66669619, 124.11238129, 162.19342648,
       126.08343682, 108.57180238, 147.82695002, 112.11996921,
       104.41961837, 231.60382343, 128.82403294, 254.98006106,
       100.87454433, 112.49017531, 160.55665635, 206.60046817,
       104.17543875, 106.3711876 ,  97.32716877,  85.12513989,
       124.49328356, 145.41340467, 231.22055672, 232.05326898,
       242.96549896, 158.91475276, 147.99652003, 198.6216418 ,
       200.85600529,  93.54483659,  73.50236459, 195.27004709,
        51.64051274, 248.25925803, 117.45234508, 208.02203894,
       250.94831906, 112.10399782, 158.34347112, 105.48723914,
       118.7440455 , 242.91953895, 144.20804009, 141.2701339 ,
        79.93701579, 149.47446683, 136.67801611, 145.64

In [36]:
from sklearn.metrics import r2_score
r2_score(y_test,model.predict(X_test))

0.4187017514936212

In [37]:
model.coef_

array([ -46.1469254 , -282.16245429,  504.43123184,  334.76026948,
       -553.4933679 ,  313.6723072 ,  -42.43395447,   99.04361604,
        679.16992502,  113.99228359])

In [50]:
X_train=np.insert(X_train,0,1,axis=1)

In [51]:
X_train

array([[ 1.        ,  0.08529891,  0.05068012, ..., -0.00259226,
         0.00286131, -0.02593034],
       [ 1.        , -0.05637009,  0.05068012, ..., -0.03949338,
        -0.07813994, -0.10463037],
       [ 1.        , -0.0854304 ,  0.05068012, ..., -0.03949338,
        -0.05780303, -0.04249877],
       ...,
       [ 1.        , -0.02730979,  0.05068012, ..., -0.03949338,
        -0.00514219, -0.05078298],
       [ 1.        , -0.02367725, -0.04464164, ...,  0.03430886,
         0.0140735 , -0.00936191],
       [ 1.        , -0.00188202, -0.04464164, ..., -0.03949338,
        -0.06833155, -0.09220405]])

# Making our own Linear Regression

In [52]:
# abhi we  have that m+1 waali cheez that mean 1  hai
X_train

array([[ 1.        ,  0.08529891,  0.05068012, ..., -0.00259226,
         0.00286131, -0.02593034],
       [ 1.        , -0.05637009,  0.05068012, ..., -0.03949338,
        -0.07813994, -0.10463037],
       [ 1.        , -0.0854304 ,  0.05068012, ..., -0.03949338,
        -0.05780303, -0.04249877],
       ...,
       [ 1.        , -0.02730979,  0.05068012, ..., -0.03949338,
        -0.00514219, -0.05078298],
       [ 1.        , -0.02367725, -0.04464164, ...,  0.03430886,
         0.0140735 , -0.00936191],
       [ 1.        , -0.00188202, -0.04464164, ..., -0.03949338,
        -0.06833155, -0.09220405]])

In [58]:
class MultipleLinearRegression:
    def __init__(self):
        self.coef_=None
        self.intercept_=None
    def fit(self,X_train,y_train):
        '''use np.linalg.inv() to find inverse'''
        self.coef_=np.linalg.inv(X_train.T.dot(X_train)).dot(X_train.T).dot(y_train)
        self.intercept_=self.coef_[0]
        print(self.intercept_,end='\n')
        self.coef_=np.delete(self.coef_,0)
        print(self.coef_ , end='\n')

    def predict(self,X_test):
       y_pred=self.intercept_ + np.dot(X_test,self.coef_)
       return y_pred


In [59]:
obj=MultipleLinearRegression()
obj.fit(X_train,y_train)
obj.predict(X_test)
# the first one is intercept

151.48483025528574
[ -46.1469254  -282.16245429  504.43123184  334.76026948 -553.4933679
  313.6723072   -42.43395447   99.04361604  679.16992502  113.99228359]


array([147.31378366, 134.8055264 ,  60.46184987, 155.06039239,
        73.37575811, 123.03940644, 188.72963279,  69.95248962,
        99.9343472 , 119.39950869, 224.17242185, 181.9774137 ,
        98.40216392,  92.53207427, 120.61217603, 152.18930744,
       119.7910676 , 204.66669619, 124.11238129, 162.19342648,
       126.08343682, 108.57180238, 147.82695002, 112.11996921,
       104.41961837, 231.60382343, 128.82403294, 254.98006106,
       100.87454433, 112.49017531, 160.55665635, 206.60046817,
       104.17543875, 106.3711876 ,  97.32716877,  85.12513989,
       124.49328356, 145.41340467, 231.22055672, 232.05326898,
       242.96549896, 158.91475276, 147.99652003, 198.6216418 ,
       200.85600529,  93.54483659,  73.50236459, 195.27004709,
        51.64051274, 248.25925803, 117.45234508, 208.02203894,
       250.94831906, 112.10399782, 158.34347112, 105.48723914,
       118.7440455 , 242.91953895, 144.20804009, 141.2701339 ,
        79.93701579, 149.47446683, 136.67801611, 145.64

In [61]:
r2_score(y_test,obj.predict(X_test))

0.41870175149362154

In [62]:
model.coef_

array([ -46.1469254 , -282.16245429,  504.43123184,  334.76026948,
       -553.4933679 ,  313.6723072 ,  -42.43395447,   99.04361604,
        679.16992502,  113.99228359])

In [63]:
model.intercept_

np.float64(151.4848302552857)